/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package visual;

/**
 *
 * @author SauloJCF
 */
public class formFinalizar extends javax.swing.JFrame {

    /**
     * Creates new form formEscolha
     */
    public formFinalizar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtCliente = new javax.swing.JLabel();
        txtRefe = new javax.swing.JLabel();
        txtFinal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        SEPARETOR = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jSeparator6 = new javax.swing.JSeparator();
        lblQuantCafe = new javax.swing.JLabel();
        lblQuantAlmoco = new javax.swing.JLabel();
        lblQuantJantar = new javax.swing.JLabel();
        lblValPag = new javax.swing.JLabel();
        lblValTot = new javax.swing.JLabel();
        lblTroco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("gerenciamento");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1080, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1080, 720));
        getContentPane().setLayout(null);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(51, 153, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(820, 500));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SysUAN");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(7, 1, 126, 36);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gerenciador");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(340, 10, 100, 19);

        jPanel5.add(jPanel1);
        jPanel1.setBounds(-1, 0, 820, 40);

        jTextField1.setBackground(new java.awt.Color(102, 102, 102));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField1.setText("Pesquisar Cliente");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel5.add(jTextField1);
        jTextField1.setBounds(20, 50, 750, 30);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(null);

        txtCliente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtCliente.setForeground(new java.awt.Color(255, 255, 255));
        txtCliente.setText("Cliente");
        jPanel3.add(txtCliente);
        txtCliente.setBounds(90, 20, 50, 19);

        txtRefe.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtRefe.setForeground(new java.awt.Color(255, 255, 255));
        txtRefe.setText("Refeição");
        jPanel3.add(txtRefe);
        txtRefe.setBounds(350, 20, 62, 19);

        txtFinal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtFinal.setForeground(new java.awt.Color(255, 255, 255));
        txtFinal.setText("Finalizar");
        jPanel3.add(txtFinal);
        txtFinal.setBounds(600, 20, 59, 19);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Valor Total:");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(520, 180, 90, 19);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Troco:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(520, 260, 60, 19);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Café da Manhã:");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(260, 90, 110, 19);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Almoço:");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(260, 180, 55, 19);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Janta:");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(260, 260, 60, 19);

        jPanel4.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("RA:");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(330, -2, 23, 40);

        jButton1.setText("Salvar");
        jButton1.setPreferredSize(new java.awt.Dimension(75, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(550, 0, 80, 30);

        jButton2.setText("Cancelar");
        jButton2.setPreferredSize(new java.awt.Dimension(75, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(640, 0, 81, 30);

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/user1.png"))); // NOI18N
        jLabel9.setText("Nome:");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(0, 0, 190, 40);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 310, 750, 40);

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Valor Pago:");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(520, 90, 100, 19);
        jPanel3.add(jSeparator5);
        jSeparator5.setBounds(500, 140, 250, 50);
        jPanel3.add(jSeparator2);
        jSeparator2.setBounds(250, 230, 250, 40);
        jPanel3.add(jSeparator7);
        jSeparator7.setBounds(500, 230, 250, 50);

        SEPARETOR.setOrientation(javax.swing.SwingConstants.VERTICAL);
        SEPARETOR.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(SEPARETOR);
        SEPARETOR.setBounds(500, 0, 250, 350);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator4);
        jSeparator4.setBounds(250, 0, 250, 350);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jSeparator3);
        jSeparator3.setBounds(0, 0, 250, 350);

        jSeparator1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(0, 0, 750, 60);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel2);
        jPanel2.setBounds(30, 80, 190, 190);
        jPanel3.add(jSeparator6);
        jSeparator6.setBounds(250, 140, 250, 50);

        lblQuantCafe.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel3.add(lblQuantCafe);
        lblQuantCafe.setBounds(420, 90, 50, 20);

        lblQuantAlmoco.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel3.add(lblQuantAlmoco);
        lblQuantAlmoco.setBounds(410, 184, 50, 20);

        lblQuantJantar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel3.add(lblQuantJantar);
        lblQuantJantar.setBounds(430, 264, 50, 20);

        lblValPag.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel3.add(lblValPag);
        lblValPag.setBounds(680, 94, 40, 20);

        lblValTot.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel3.add(lblValTot);
        lblValTot.setBounds(690, 180, 40, 20);

        lblTroco.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jPanel3.add(lblTroco);
        lblTroco.setBounds(690, 264, 40, 20);

        jPanel5.add(jPanel3);
        jPanel3.setBounds(20, 90, 750, 350);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 0, 802, 457);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formFinalizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formFinalizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formFinalizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formFinalizar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formFinalizar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator SEPARETOR;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblQuantAlmoco;
    private javax.swing.JLabel lblQuantCafe;
    private javax.swing.JLabel lblQuantJantar;
    private javax.swing.JLabel lblTroco;
    private javax.swing.JLabel lblValPag;
    private javax.swing.JLabel lblValTot;
    private javax.swing.JLabel txtCliente;
    private javax.swing.JLabel txtFinal;
    private javax.swing.JLabel txtRefe;
    // End of variables declaration//GEN-END:variables
}
